### ISSUE TITLE
Code housekeeping.

### ISSUE THREAD

**Issue by michaelcoyote** [pysheng/pysheng#22]
I've noticed that a number of the files don't pass `flake8` (the PEP8 linter) cleanly and it appears that most of this stuff is just minor housekeeping stuff like spacing, indentation and line length.  Since I was planning to work on the code anyway, I'd like to volunteer myself to do some of this housekeeping.  
I wanted to open the issue here to track and let people know what I was doing before sending in a bunch of pull requests w/o context.

I figure I'd just send in a few files at a time with the `flake8` output in the PR comments for reference.

**Comment by tokland** [comment]
Great, the code certainly needs some care.

**Comment by tokland** [comment]
I am not actively developing this package anymore, sorry, I hope some user with Python experience can take it in a fork.

**Comment by michaelcoyote** [comment]
Transfer it to it's own org and I'll see what I can do.  Job and new baby duties might make for slow going from me, but I'm looking to do some more cleanup.

**Comment by tokland** [comment]
Project transferred to https://github.com/pysheng/pysheng

@michaelcoyote you should have received an invitation

Thanks!

**Comment by michaelcoyote** [comment]
Looks like the deed is done.  TY

**Comment by michaelcoyote** [comment]
The first round of cleanup has been done for a while.  I'm going to close this for now, but there needs to be some more structural work done.
